const viewports=['macbook-15','iphone-6']
viewports.forEach((vp)=>{
    describe(`registroWrongPath:${vp}`,()=>{
        beforeEach(()=>{
            cy.viewport(vp)
            cy.visit('https://ticketazo.com.ar/auth/registerUser')
        })
        it('sinDatos',()=>{
            cy.get('[data-cy="btn-registrarse"]').click()
            cy.get('[data-slot="error-message"]').eq(0)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(1)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(2)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(3)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(4)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(5)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(6)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(7)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(8)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(9)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
            cy.get('[data-slot="error-message"]').eq(10)
            .contains(/Completa este campo|Please fill out this field/).should('be.visible')
        })
        it('dniIncompleto',()=>{
            cy.get('[data-cy="input-dni"]').type('0').blur()
            cy.contains('[data-slot="error-message"]',/Utiliza un formato que coincida con el solicitado|Please match the requested format./).should('be.visible')
        })
        it('dniIncompleto',()=>{
            cy.get('[data-cy="input-dni"]').type('0').blur()
            cy.contains('[data-slot="error-message"]',/Utiliza un formato que coincida con el solicitado|Please match the requested format./).should('be.visible')
        })
        it('fechaInvalida',()=>{
            cy.get('[data-type="day"]').type('30')
            cy.get('[data-type="month"]').type('12')
            cy.get('[data-type="year"]').type('9999').blur()
            cy.contains('[data-slot="error-message"]',/El valor debe ser|Value must be/).should('be.visible')
        })
        it('sinArroba',()=>{
            cy.get('[data-cy="input-email"]').type('asd').blur()
            cy.get('[data-slot="error-message"]').invoke('text')
            .should('match',/Incluye un signo "@" en la dirección de correo electrónico|Please include an '@' in the email address/)
        })
        it('sinTextoPostArroba',()=>{
            cy.get('[data-cy="input-email"]').type('asd@').blur()
            cy.get('[data-slot="error-message"]').invoke('text')
            .should('match',/Introduce texto detrás del signo "@"|Please enter a part following '@'/)
        })
        it('simboloPostArroba',()=>{
            cy.get('[data-cy="input-email"]').type('test@=.com').blur()
            cy.get('[data-slot="error-message"]').invoke('text')
            .should('match',/El texto detrás del signo "@" no debe incluir el símbolo|A part following '@' should not contain the symbol/)
        })
        it('puntoPostArroba',()=>{
            cy.get('[data-cy="input-email"]').type('a@.').blur()
            cy.get('[data-slot="error-message"]').invoke('text')
            .should('match',/El signo "." está colocado en una posición incorrecta en la dirección|'.' is used at a wrong position in/)
        })
        it('correoInvalido',()=>{
            cy.get('[data-cy="input-nombres"]').type('Termotanque')
            cy.get('[data-cy="input-apellido"]').type('Derravioles')
            cy.get('[data-cy="input-telefono"]').type('1234567890')
            cy.get('[data-cy="input-dni"]').type('12345678')
            cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
            cy.get('[data-cy="select-localidad"]').type('Cordoba{enter}')
            cy.get('[data-type="day"]').type('20')
            cy.get('[data-type="month"]').type('5')
            cy.get('[data-type="year"]').type('1901')
            cy.get('[data-cy="input-email"]').type('a@com')
            cy.get('[data-cy="input-confirmar-email"]').type('a@com')
            cy.get('[data-cy="input-password"]').type('Adm1n???')
            cy.get('[data-cy="input-repetir-password"]').type('Adm1n???')
            cy.get('[data-cy="btn-registrarse"]').click()
            cy.get('[data-cy="error-message"]')
            .contains('El correo electrónico no es válido')
            .should('be.visible')
        })
        it('passInvalida',()=>{
            cy.get('[data-cy="input-nombres"]').type('Juan')
            cy.get('[data-cy="input-apellido"]').type('Carlo')
            cy.get('[data-cy="input-telefono"]').type('1234567890')
            cy.get('[data-cy="input-dni"]').type('12345678')
            cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
            cy.get('[data-cy="select-localidad"]').type('Cordoba{enter}')
            cy.get('[data-type="day"]').type('20')
            cy.get('[data-type="month"]').type('5')
            cy.get('[data-type="year"]').type('1901')
            cy.get('[data-cy="input-email"]').type('asd@asd.com')
            cy.get('[data-cy="input-confirmar-email"]').type('asd@asd.com')
            cy.get('[data-cy="input-password"]').type('123456')
            cy.get('[data-cy="input-repetir-password"]').type('123456')
            cy.get('[data-cy="btn-registrarse"]').click()
            cy.get('[data-cy="error-message"]')
            .contains('La contraseña debe tener al menos 8 caracteres, incluyendo mayúsculas, minúsculas, números y símbolos.')
            .should('be.visible')
        })
    })
})