describe('mensajeErrorPass',()=>{
    beforeEach(()=>{
        cy.visit('https://ticketazo.com.ar/auth/registerUser')
    })
    
    it('simboloPostArroba', ()=>{
        cy.get('[data-cy="input-nombres"]').type('Juan')
        cy.get('[data-cy="input-apellido"]').type('Carlo')
        cy.get('[data-cy="input-telefono"]').type('1234567890')
        cy.get('[data-cy="input-dni"]').type('12345678')
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').type('Cordoba{enter}')
        cy.get('[data-type="day"]').type('20')
        cy.get('[data-type="month"]').type('5')
        cy.get('[data-type="year"]').type('1901')
        cy.get('[data-cy="input-email"]').type('test@=.com')
        cy.get('[data-cy="input-confirmar-email"]').type('test@=.com')
        cy.wait(2000)
        cy.get('[data-slot="error-message"]')
        .should('include.text','El texto detrás del signo "@" no debe incluir el símbolo')
    })

    it('sinArroba', ()=>{
        cy.get('[data-cy="input-nombres"]').type('Juan')
        cy.get('[data-cy="input-apellido"]').type('Carlo')
        cy.get('[data-cy="input-telefono"]').type('1234567890')
        cy.get('[data-cy="input-dni"]').type('12345678')
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').type('Cordoba{enter}')
        cy.get('[data-type="day"]').type('20')
        cy.get('[data-type="month"]').type('5')
        cy.get('[data-type="year"]').type('1901')
        cy.get('[data-cy="input-email"]').type('asd')
        cy.get('[data-cy="input-confirmar-email"]').type('asd')
        cy.wait(2000)
        cy.get('[data-slot="error-message"]')
        .should('include.text','Incluye un signo "@" en la dirección de correo electrónico. La dirección')
    })
    
    it('passInvalida', ()=>{
        cy.get('[data-cy="input-nombres"]').type('Juan')
        cy.get('[data-cy="input-apellido"]').type('Carlo')
        cy.get('[data-cy="input-telefono"]').type('1234567890')
        cy.get('[data-cy="input-dni"]').type('12345678')
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').type('Cordoba{enter}')
        cy.get('[data-type="day"]').type('20')
        cy.get('[data-type="month"]').type('5')
        cy.get('[data-type="year"]').type('1901')
        cy.get('[data-cy="input-email"]').type('asd@asd.com')
        cy.get('[data-cy="input-confirmar-email"]').type('asd@asd.com')
        cy.get('[data-cy="input-password"]').type('123456')
        cy.get('[data-cy="input-repetir-password"]').type('123456')
        cy.get('[data-cy="btn-registrarse"]').click()
        cy.wait(2000)
        cy.get('[data-cy="error-message"]')
        .contains('La contraseña debe tener al menos 8 caracteres, incluyendo mayúsculas, minúsculas, números y símbolos.')
    })
})